[output]
path ="/home/alexey/code/rss-poller/out"

[input]
links = [
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/front_page/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/world/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/northern_ireland/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/scotland/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/wales/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/business/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/uk_politics/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/health/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/education/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/sci/tech/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/technology/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/entertainment/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/talking_point/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/magazine/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsplayer_uk_edition/uk/rss.xml",
"http://newsrss.bbc.co.uk/rss/newsplayer_uk_edition/world/rss.xml",

"https://lenta.ru/rss",

"http://rss.cnn.com/rss/edition_world.rss",
"http://rss.cnn.com/rss/edition_africa.rss",
"http://rss.cnn.com/rss/edition_americas.rss",
"http://rss.cnn.com/rss/edition_asia.rss",
"http://rss.cnn.com/rss/edition_europe.rss",
"http://rss.cnn.com/rss/edition_meast.rss",
"http://rss.cnn.com/rss/edition_us.rss",
"http://rss.cnn.com/rss/money_news_international.rss",
"http://rss.cnn.com/rss/edition_technology.rss",
"http://rss.cnn.com/rss/edition_space.rss",
"http://rss.cnn.com/rss/edition_entertainment.rss",
"http://rss.cnn.com/rss/edition_sport.rss",
"http://rss.cnn.com/rss/edition_football.rss",
"http://rss.cnn.com/rss/edition_golf.rss",
"http://rss.cnn.com/rss/edition_motorsport.rss",
"http://rss.cnn.com/rss/edition_tennis.rss",
"http://rss.cnn.com/rss/edition_travel.rss",
"http://rss.cnn.com/rss/cnn_latest.rss",

"https://www.cnbc.com/id/100003114/device/rss/rss.html",
"https://www.cnbc.com/id/100727362/device/rss/rss.html",
"https://www.cnbc.com/id/15837362/device/rss/rss.html",
"https://www.cnbc.com/id/19832390/device/rss/rss.html",
"https://www.cnbc.com/id/19794221/device/rss/rss.html",
"https://www.cnbc.com/id/10001147/device/rss/rss.html",
"https://www.cnbc.com/id/15839135/device/rss/rss.html",
"https://www.cnbc.com/id/100370673/device/rss/rss.html",
"https://www.cnbc.com/id/20910258/device/rss/rss.html",
"https://www.cnbc.com/id/10000664/device/rss/rss.html",
"https://www.cnbc.com/id/19854910/device/rss/rss.html",
"https://www.cnbc.com/id/10000113/device/rss/rss.html",
"https://www.cnbc.com/id/10000108/device/rss/rss.html",
"https://www.cnbc.com/id/10000115/device/rss/rss.html",
"https://www.cnbc.com/id/10001054/device/rss/rss.html",
"https://www.cnbc.com/id/10000101/device/rss/rss.html",
"https://www.cnbc.com/id/19836768/device/rss/rss.html",
"https://www.cnbc.com/id/10000110/device/rss/rss.html",
"https://www.cnbc.com/id/10000116/device/rss/rss.html",
"https://www.cnbc.com/id/10000739/device/rss/rss.html",
"https://www.cnbc.com/id/44877279/device/rss/rss.html",

"http://ep00.epimg.net/rss/elpais/portada.xml",
"http://ep00.epimg.net/rss/cat/portada.xml",
"http://ep00.epimg.net/rss/elpais/portada_america.xml",
"http://ep00.epimg.net/rss/brasil/portada.xml",
"http://ep00.epimg.net/rss/internacional/portada.xml",
"http://ep00.epimg.net/rss/politica/portada.xml",
"http://ep00.epimg.net/rss/ccaa/andalucia.xml",
"http://ep00.epimg.net/rss/ccaa/catalunya.xml",
"http://ep00.epimg.net/rss/ccaa/valencia.xml",
"http://ep00.epimg.net/rss/ccaa/madrid.xml",
"http://ep00.epimg.net/rss/ccaa/paisvasco.xml",
"http://ep00.epimg.net/rss/ccaa/galicia.xml",
"http://ep00.epimg.net/rss/economia/portada.xml",
"http://ep00.epimg.net/rss/elpais/ciencia.xml",
"http://ep00.epimg.net/rss/tecnologia/portada.xml",
"http://ep00.epimg.net/rss/cultura/portada.xml",
"http://ep00.epimg.net/rss/deportes/portada.xml",
"http://ep00.epimg.net/rss/sociedad/portada.xml",

"http://estaticos.elmundo.es/elmundo/rss/portada.xml",
"http://estaticos.elmundo.es/elmundo/rss/espana.xml",
"http://estaticos.elmundo.es/elmundo/rss/internacional.xml",
"http://estaticos.elmundo.es/elmundo/rss/union_europea.xml",
"http://estaticos.elmundo.es/elmundo/rss/economia.xml",
"http://estaticos.elmundo.es/elmundo/rss/cultura.xml",
"http://estaticos.elmundo.es/elmundo/rss/ciencia.xml",
"http://estaticos.elmundo.es/elmundo/rss/madrid.xml",
"http://estaticos.elmundo.es/elmundo/rss/barcelona.xml",
"http://estaticos.elmundo.es/elmundo/rss/baleares.xml",
"http://estaticos.elmundo.es/elmundo/rss/castillayleon.xml",
"http://estaticos.elmundo.es/elmundo/rss/valladolid.xml",
"http://estaticos.elmundo.es/elmundo/rss/valencia.xml",
"http://estaticos.elmundo.es/elmundo/rss/alicante.xml",
"http://estaticos.elmundo.es/elmundo/rss/castellon.xml",
"http://estaticos.elmundo.es/elmundo/rss/paisvasco.xml",
"http://estaticos.elmundo.es/elmundo/rss/andalucia.xml",
"http://estaticos.elmundo.es/elmundo/rss/andalucia_sevilla.xml",
"http://estaticos.elmundo.es/elmundo/rss/andalucia_malaga.xml",
"http://estaticos.elmundo.es/elmundo/rss/solidaridad.xml",
"http://estaticos.elmundo.es/elmundo/rss/comunicacion.xml",
"http://estaticos.elmundo.es/elmundo/rss/television.xml",
"http://estaticos.elmundo.es/elmundo/rss/suvivienda.xml",
"http://estaticos.elmundo.es/elmundodeporte/rss/portada.xml",
"http://estaticos.elmundo.es/elmundodeporte/rss/futbol.xml",
"http://estaticos.elmundo.es/elmundodeporte/rss/baloncesto.xml",
"http://estaticos.elmundo.es/elmundodeporte/rss/ciclismo.xml",
"http://estaticos.elmundo.es/elmundodeporte/rss/golf.xml",
"http://estaticos.elmundo.es/elmundodeporte/rss/tenis.xml",
"http://estaticos.elmundo.es/elmundodeporte/rss/motor.xml",
"http://estaticos.elmundo.es/elmundodeporte/rss/masdeporte.xml",

"http://www.france24.com/en/top-stories/rss",
"http://www.france24.com/en/europe/rss",
"http://www.france24.com/en/france/rss",
"http://www.france24.com/en/africa/rss",
"http://www.france24.com/en/middle-east/rss",
"http://www.france24.com/en/americas/rss",
"http://www.france24.com/en/asia-pacific/rss",
"http://www.france24.com/en/business-tech/rss",
"http://www.france24.com/en/culture/rss",

"http://rss.dw.com/rdf/rss-en-all",
"http://rss.dw.com/rdf/rss-en-ger",
"http://rss.dw.com/rdf/rss-en-world",
"http://rss.dw.com/rdf/rss-en-eu",
"http://rss.dw.com/rdf/rss-en-bus",
"http://rss.dw.com/xml/rss_en_science",
"http://rss.dw.com/xml/rss_en_environment",
"http://rss.dw.com/rdf/rss-en-cul",
"http://partner.dw.com/rdf/rss-en-sports",
"http://rss.dw.com/rdf/rss-en-asia",

"https://www.aljazeera.com/xml/rss/all.xml",

"https://www.channelnewsasia.com/rssfeeds/8395986",
"https://www.channelnewsasia.com/rssfeeds/8395744",
"https://www.channelnewsasia.com/rssfeeds/8395954",
"https://www.channelnewsasia.com/rssfeeds/8396082",
"https://www.channelnewsasia.com/rssfeeds/8395838",
"https://www.channelnewsasia.com/rssfeeds/8395884",

"http://feeds.skynews.com/feeds/rss/home.xml",
"http://feeds.skynews.com/feeds/rss/uk.xml",
"http://feeds.skynews.com/feeds/rss/world.xml",
"http://feeds.skynews.com/feeds/rss/us.xml",
"http://feeds.skynews.com/feeds/rss/business.xml",
"http://feeds.skynews.com/feeds/rss/politics.xml",
"http://feeds.skynews.com/feeds/rss/technology.xml",
"http://feeds.skynews.com/feeds/rss/entertainment.xml",
"http://feeds.skynews.com/feeds/rss/strange.xml"
]
